# Brevo API Configuration
brevo.api.key=${BREVO_API_KEY}
brevo.api.url=${BREVO_API_URL:https://api.brevo.com/v3/smtp/email}
brevo.sender.email=${BREVO_SENDER_EMAIL:no-reply@mhdc.co.id}
brevo.sender.name=${BREVO_SENDER_NAME:No Reply - Laporan MHDC Ruang Bicara}
server.port=${SERVER_PORT:8080}

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=
#spring.mail.password=
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true